server:
  port: 80
discord:
  client:
    clientId: ${VEGGIE_CLIENT_ID}
    clientSecret: ${VEGGIE_CLIENT_SECRET}
    accessTokenUri: https://discordapp.com/api/oauth2/token
    userAuthorizationUri: https://discordapp.com/api/oauth2/authorize
    scope: identify
    clientAuthenticationScheme: query
  resource:
    userInfoUri: https://discordapp.com/api/users/@me